### ISSUE TITLE
Work with Preview 5?

### ISSUE THREAD

**Issue by aherrick** [jsakamoto/Toolbelt.Blazor.I18nText#1]
Does this work with Preview 5? I've installed the Nuget package but not seeing anything generated on build.

**Comment by jsakamoto** [comment]
It would be works fine also on .NET Core 3.0/Client-side Blazor Preview 5.

I created sample project "Demo1" just now from "dotnet new blazor" and followed instructions of README.md, it works fine.

[Demo1.zip](https://github.com/jsakamoto/Toolbelt.Blazor.I18nText/files/3237437/Demo1.zip)

Could you provide the source code of your case?

**Comment by aherrick** [comment]
Thank you! Going to look at the demo.
