### ISSUE TITLE
How wire up the API's

### ISSUE THREAD

**Issue by T-Alkathiri** [jsakamoto/Toolbelt.Blazor.I18nText#15]
Dear sir,
Thank you very much for this great solution.
If you please post a small example on how to use the api's with this solution will be very appreciated.
Again thank you very much for that.

**Comment by jsakamoto** [comment]
Is the sample code bellow helpful for you?

https://github.com/jsakamoto/Toolbelt.Blazor.I18nText/blob/master/Tests/Client/Shared/MainLayout.razor

The sample code above describes how to retrieve the current language, and how to change the current language.
