### ISSUE TITLE
Play nicely with Stylecop

### ISSUE THREAD

**Issue by paulstringerdb** [jsakamoto/Toolbelt.Blazor.I18nText#17]
Perhaps the comment for "auto generated" could be modified to play nicely with Stylecop ?

i.e.

`// <auto-generated by="Generated by the Blazor I18n Text compiler" />`

This will no longer produce errors/warnings in the generated code :-)

**Comment by jsakamoto** [comment]
Thank you for your nice suggestion!

I'll do this in these days.

**Comment by jsakamoto** [comment]
@paulstringerdb 

 I published "Blazor i18ntext" v.7.1.

- https://www.nuget.org/packages/Toolbelt.Blazor.I18nText/7.1.0

Please check it out!
