### ISSUE TITLE
Not working in  Blazor v.3.2 preview 2

### ISSUE THREAD

**Issue by tomasgerhardsen** [jsakamoto/Toolbelt.Blazor.I18nText#22]
Static content is handled differently in Blazor v.3.2 preview 2. There is no dist folder. should be published to wwwroot folder instead

https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/

**Comment by jsakamoto** [comment]
@tomasgerhardsen Thanks for heads up me!

I'm working on update the "Blazor I18nText" to be suitable for Blazor v.3.2 preview 2.

Please wait for a few days!

**Comment by jsakamoto** [comment]
I published "Blazor I18n Text" ver.9.0.0 for Blazor v.3.2 preview 2, just now.

- https://www.nuget.org/packages/Toolbelt.Blazor.I18nText/

Let's try it!
