### ISSUE TITLE
Translation on azure

### ISSUE THREAD

**Issue by brux88** [jsakamoto/Toolbelt.Blazor.I18nText#24]
hello to me it works locally but when I publish on azure I can't find the translations, what could it be? i am using blazor webassembly

**Comment by jsakamoto** [comment]
@brux88 Thank you for your report!

I'm working on solving this issue.

The changes by upgrading the Blazor build system in these days must break it.

The workaround of at this time is using dotnet CLI to publishing.

**Comment by jsakamoto** [comment]
I fixed this problem just now.

Please try ver.9.0.1 out.

- https://www.nuget.org/packages/Toolbelt.Blazor.I18nText/9.0.1

**Comment by brux88** [comment]
thank you now work
