### ISSUE TITLE
blazor preview 5

### ISSUE THREAD

**Issue by brux88** [jsakamoto/Toolbelt.Blazor.I18nText#27]
I rpovato to update blazor to preview 5 but gives me an error:
Microsoft.JSInterop.JSException: Could not find 'getSatelliteAssemblies'  

I think it's tied to your package, can it be?

**Comment by jsakamoto** [comment]
I upgraded the sample sites to Blazor v.3.2 Preview 5 (see commit 19427d07e796c0fa6e0575acc6a2319e36e059dd), but it looks work fine.

Will be the comment below helpful for you?

- https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-4-release-now-available/#comment-1869
