### ISSUE TITLE
Expose "ChangeLanguage" Event Handler

### ISSUE THREAD

**Issue by nwestfall** [jsakamoto/Toolbelt.Blazor.I18nText#35]
Would it be possible to expose the `ChangeLanguage` event handler in the text repository?  I have a few use cases where I could love to know if another part of the application changed the language.

Is this something you'd be willing to support?  I can do a PR if you think the feature would be beneficial.

**Comment by jsakamoto** [comment]
Thank you for your proposal! 👍 

But unfortunately, currently, I'm busy because I have some issue reports due to I publish so many NuGet packages 😅

However, of course, I'm interested in your proposal very much! 
Please give me a few days, I'll consider your proposal.

**Comment by nwestfall** [comment]
I understand! Let me know if I can help in any way!

**Comment by jsakamoto** [comment]
(I waked up at this morning 7:00am. I'm live in Japan!)

@nwestfall Thank you for your understanding and contribution. 👍

**Comment by jsakamoto** [comment]
@nwestfall Thank you for waiting!

At last, I merged your pull request and published it as ver.9.3.0 🎉 

- https://www.nuget.org/packages/Toolbelt.Blazor.I18nText/9.3.0

Again, thank you for your contribution! 👍
