### ISSUE TITLE
update for .NET 5.0 ?

### ISSUE THREAD

**Issue by fabianus76** [jsakamoto/Toolbelt.Blazor.I18nText#37]
Hi Jsakamoto, 

what about ASP.NET 5.0 ?

**Comment by jsakamoto** [comment]
Yes, I'll support .NET 5.

I already started to try to run this library on .NET5. The current version of this library will work fine on also .NET5.

See also `add-support-net5` branch: https://github.com/jsakamoto/Toolbelt.Blazor.I18nText/compare/improve/add-support-net5

**Comment by fabianus76** [comment]
yes, works fine - thanks Jsakamoto. 
Thanks for continuing - this is not replacable by the integrated localisation of Blazor !
