### ISSUE TITLE
Can this be used with Xamarin.Forms?

### ISSUE THREAD

**Issue by amoraitis** [jsakamoto/Toolbelt.Blazor.I18nText#38]
Hi, can this solution work with a Xamarin.Forms project and MVVM?

This ` <TargetFramework>netstandard2.0</TargetFramework>` makes me think that it should.

**Comment by jsakamoto** [comment]
@amoraitis I'm not familiar with Xamarin.Forms, but this library will not be available for localizing Xamarin.Forms application, I think. 

For example, this library depends on "IJSRuntime" service (the service for interoperability with JavaScript engine on a Web browser) strongly.

**Comment by amoraitis** [comment]
Thank you for your answer. I don't have that experience with the IJSRuntime to know whether it can be used on mobile or not. I am closing this. For others, interesting in using a library for both Xamarin and Blazor, I went with the `Embedded.Json.Localization` NuGet.
