### ISSUE TITLE
Blazor preview6 -- > preview7 :Json library breaking changes

### ISSUE THREAD

**Issue by Psimatrix** [jsakamoto/Toolbelt.Blazor.I18nText#4]
In my project I am getting 

"Unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.Void Toolbelt.Blazor.I18nText.I18nText/<FetchTextTableAsync>d__16`1::MoveNext()' in assembly: 'Toolbelt.Blazor.I18nText.dll'"

There seems to be a breaking change in Json libraries used. To summarize

preview6  ==> Preview7
1) Json librarySystem.Text.Json.Serialization => System.Text.Json
2) JsonSerializer.Parse => JsonSerializer.Deserialize
3) JsonSerializer.ToString => JsonSerializer.Serialize

**Comment by Psimatrix** [comment]
I've confirmed that the issue can be simply updated with changes in the I18nText.cs

JsonSerializer.Parse --> .Deserialize

and updating to latest latest preview version

<PackageReference Include="Microsoft.AspNetCore.Components.Browser" Version="3.0.0-preview7.19365.7" />

in project file.

**Comment by jsakamoto** [comment]
Thank you for your reporting!
It is very very helpful for me.

Just now, I published new version of "Blazor I18n Text" NuGet package for support Blazor v.3.0 Preview 7.

I could not fix this issue without your report.

Thanks!
