### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by be-swarm** [jsakamoto/Toolbelt.Blazor.I18nText#46]
Hi,
With the latest version i got:
Error: System.InvalidOperationException: Cannot resolve scoped service 'Toolbelt.Blazor.I18nText.Internals.HelperScript' from root provider.

Thanks

**Comment by jsakamoto** [comment]
@be-swarm 
Thank you for reporting!

I fixed the bug and published the new version of the Blazor I18n Text package.

- https://www.nuget.org/packages/Toolbelt.Blazor.I18nText/11.1.3

Please try it out. 😃

**Comment by be-swarm** [comment]
Perfect 👍Thanks.Envoyé de mon Galaxy S20+ 5G Orange
-------- Message d'origine --------De : jsakamoto ***@***.***> Date : 05/02/2022  13:38  (GMT+01:00) À : "jsakamoto/Toolbelt.Blazor.I18nText" ***@***.***> Cc : BE SWARM ***@***.***>, Mention ***@***.***> Objet : Re: [jsakamoto/Toolbelt.Blazor.I18nText] exception (Issue #46) 

@be-swarm

Thank you for reporting!

I fixed the bug and published the new version of the Blazor I18n Text package.



https://www.nuget.org/packages/Toolbelt.Blazor.I18nText/11.1.3



Please try it out. 😃
