### ISSUE TITLE
Stopped working after updating to .NET7 preview 2

### ISSUE THREAD

**Issue by Alikhll** [jsakamoto/Toolbelt.Blazor.I18nText#50]
I have been receiving 404 error message while request toward json items being made!

**Comment by jsakamoto** [comment]
@Alikhll Thank you for letting me know!

I fixed this problem today.
Could you try the latest version of the "Blazor I18n Text" NuGet package?

- https://www.nuget.org/packages/Toolbelt.Blazor.I18nText/11.1.4
