### ISSUE TITLE
Release 8 Updates

### ISSUE THREAD

**Issue by Psimatrix** [jsakamoto/Toolbelt.Blazor.I18nText#6]
Any idea when you will have the release 8 updates in place. Several breaking changes. Thanks!

**Comment by jsakamoto** [comment]
Thank you for your post!

It is hard work, but I'm doing now.

f1f8ea90b96b2bedd518c91358b4ad427d7d1704

I want to finish this work until next week.

**Comment by Psimatrix** [comment]
Thanks for the update and your work. You'll likely find this yourself. but you also need to change any package references of 

Microsoft.AspNetCore.Components.Browser to 
Microsoft.AspNetCore.Components.Web 

https://www.nuget.org/packages/Microsoft.AspNetCore.Components.Web/. 


Without this update looks like project will give linker errors

Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Threading.Tasks.Task Microsoft.AspNetCore.Components.Browser.RendererRegistryEventDispatcher::DispatchEvent(Microsoft.AspNetCore.Components.Browser.RendererRegistryEventDispatcher/BrowserEventDescriptor,System.String)' in assembly: 'Microsoft.AspNetCore.Components.Browser.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.Tasks.Task Microsoft.AspNetCore.Components.Rendering.Renderer::DispatchEventAsync(System.Int32,Microsoft.AspNetCore.Components.Rendering.EventFieldInfo,Microsoft.AspNetCore.Components.UIEventArgs)

**Comment by jsakamoto** [comment]
@Psimatrix Thanks for your detail report!

I published the new version of this package just now for Blazor ver.3.0.0-preview8 support.

- https://www.nuget.org/packages/Toolbelt.Blazor.I18nText/5.0.0.19

I hope this version works fine on Blazor ver.3.0.0-preview8.
