### ISSUE TITLE
Does not seem to work with server-side Blazor

### ISSUE THREAD

**Issue by heteibako** [jsakamoto/Toolbelt.Blazor.I18nText#9]
I get this error message when I run the program
Did the step by step instructions.

  | Message | "One or more errors occurred. (Could not find 'Toolbelt' in 'window'.\nError: Could not find 'Toolbelt' in 'window'.\n    at https://localhost:5001/_framework/blazor.server.js:8:28065\n    at Array.forEach (<anonymous>)\n    at p (https://localhost:5001/_framework/blazor.server.js:8:28026)\n    at https://localhost:5001/_framework/blazor.server.js:8:28733\n    at new Promise (<anonymous>)\n    at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:8:28707)\n    at https://localhost:5001/_framework/blazor.server.js:1:19148\n    at Array.forEach (<anonymous>)\n    at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:19119)\n    at e.processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:17165))" | string

**Comment by jsakamoto** [comment]
I'm sorry that server-side Blazor  is not supported at this time.

(from README)
![image](https://user-images.githubusercontent.com/95908/64741059-396c7100-d532-11e9-848a-e8f4ede54c98.png)

I want to support server-side Blazor, I'll try to it, but it will need more days.

**Comment by NPadrutt** [comment]
Would love to see that work with service side. I switch often to server side so that I can debug. :)

**Comment by agonzalezm** [comment]
I also use server-side, any plan to support server-side blazor? and how will this work for data annotations messages.

**Comment by jsakamoto** [comment]
Thank you for request!

Sorry for keeping you waiting for such a long time.  
Today, I supported **Server-Side Blazor**!

[![image](https://user-images.githubusercontent.com/95908/66169898-ebecab00-e67c-11e9-9d6a-5152fa5b8725.png)](https://twitter.com/jsakamoto/status/1179751704041902081)

>  and how will this work for data annotations messages.

However, this version still not support data annotations messages.  
I would like to support it, so please give me a few weeks.
